server:
  listen_address: tcp://0.0.0.0:9000 # (tcp/tls)://IP:PORT
  context: []
  events: []

connector:
  connections:
    - address: 127.0.0.1:9000
      type: bind_transceiver
      systemId: example
      password: password
  options: []
  events: []

log:
  name: smsc
  handler: php://stdout # php://stdout or filename
  level: DEBUG # Possible values: DEBUG INFO NOTICE WARNING ERROR CRITICAL ALERT EMERGENCY
